Chapter1/homework/cooking new
Almantask/Java-Homework pull request #116
Opened 2020-11-27 19:52 UTC by EdvinasA

I don't know if i did correctly with exceptions but i tried to put in exceptions in methods were they fitted, also created recipe processing from file, you need to enter file location and name if file is in java-homework folder you only need to enter the name of the file, also fixed reading recipes, now no matter the order it will print ingredient first amount second and unit third, haven't implemented if there are missing some of the parts of recipe. also used arrayLists for finding recipe parts.

Implemented tests.

haven't figured out yet how to remove units and put them in enum class with amounts.

2020-11-28 17:24 UTC, Almantask requested changes

2020-11-28 17:24 UTC, Almantask commented on src/main/java/CookingConvertor/Amounts.java
> +    }
No longer needed- enum represents that string.

2020-11-28 17:24 UTC, Almantask commented on src/main/java/CookingConvertor/Cooking.java
> +    }
The whole class can now be removed, because you use enums

2020-11-28 17:24 UTC, Almantask commented on src/main/java/CookingConvertor/Cooking.java
> +    }
Enum is always valid

2020-11-28 17:24 UTC, Almantask commented on tests/CookingConvertor/CookingMeasurementConverterTest.java
> +class CookingMeasurementConverterTest {
Missing many tests

2020-11-29 12:45 UTC, EdvinasA commented on src/main/java/CookingConvertor/Cooking.java
> +
Removed Units class

2021-01-15 05:54 UTC, closed without merging